name: llm-from-scratch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.10.13
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - gcc
  - pip
  - pip:
    - -r requirements.txt

